In [1]:
import numpy as np

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [8]:
# Unlike lists, all the elements should be of the same data type in numpy arrays
arr1 = np.array([1,3,4])
arr2 = np.array([[1,2,3],[4,5,6]])

# Creating a numpy array of dimension 3,4 with all elements as zero
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# Creating a numpy array of dimension 3,5, with all elements as ones
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
# Creating a numpy array of dimension 4,6, filled with a particular values
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [12]:
# Creating an Identity matrix (main diagnol all ones, rest all elements are zeroes) - Creating an identity matrix of order 5
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Used to create a NumPy array in which the elements lie in a particular range along with the skip number
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [17]:
# Use to create evenly spaced arrays
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [21]:
my_arr.shape

(4, 3)

In [22]:
my_arr.size

12

In [23]:
my_arr.ndim

2

In [24]:
my_arr.dtype

dtype('int64')

In [33]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float64')
my_arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [34]:
my_arr.dtype

dtype('float64')

In [38]:
# Converting the data type of a list into some other data type
my_arr = my_arr.astype(np.int64)

In [39]:
my_arr.dtype

dtype('int64')

In [40]:
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [43]:
reshaped = my_arr.reshape(3,4)
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [44]:
# While reshaping the total number of elements should be same
reshaped = my_arr.reshape(2,6)
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [45]:
# Flatten will convert this into a 1-D Array
flatten_array = reshaped.flatten()

In [46]:
flatten_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])