In [1]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [5]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
print(flat[0])

1


In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
 # Getting every second element from the numpy array
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [13]:
# SLICING RETURNS A VIEW NOT A COPY ! NUMPY ARRAY DOES NOT CREATE A COPY ! PYTHON LISTS CREATE A COPY
# This makes numpy array faster since same memory location is being referred
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [14]:
b = flat[3:7]

In [15]:
b

array([4, 5, 6, 7])

In [16]:
b[0] = 444444

In [17]:
b

array([444444,      5,      6,      7])

In [18]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [19]:
# What if we want to create a copy
b = flat[3:7].copy()

In [20]:
b

array([444444,      5,      6,      7])

In [21]:
b[1]=9834
b

array([444444,   9834,      6,      7])

In [23]:
# Now this won't affect the original numpy array
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     11,     12,     13])

In [24]:
# Fancy indexing
arr = np.array([1,54,23,53,2,3,34,5,6])

In [25]:
# index = [1,4,6]
# arr[index]
arr[[1,4,6]]

array([54,  2, 34])

In [26]:
# Boolean Masking (filtering on the basis of a condition)
arr[arr>3]

array([54, 23, 53, 34,  5,  6])

In [27]:
arr[arr>23]

array([54, 53, 34])