In [6]:
import numpy as np
import random 

In [15]:
random_array = np.random.randint(1,100,size=(3,3))
random_array

array([[87, 93,  8],
       [14, 54,  5],
       [85, 40, 24]])

In [17]:
random_array.shape

(3, 3)

In [27]:
array_of_floats = np.array([1.1, 2.2, 3.3])
array_of_floats.dtype

dtype('float64')

In [28]:
array_of_floats = array_of_floats.astype('int64')

In [29]:
array_of_floats

array([1, 2, 3])

In [30]:
array_of_floats.dtype

dtype('int64')

In [41]:
fancy = np.array([1, 2, 3, 4, 5, 6])
even_mask = fancy % 2 == 0
even_mask

array([False,  True, False,  True, False,  True])

In [42]:
fancy = fancy[even_mask]
fancy

array([2, 4, 6])

In [48]:
one_d = np.full(9,8)

In [49]:
np.reshape(one_d,(3,3))

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [50]:
boolean_masking = np.array([1,2,3,4,55,394,32,53,4,32,5,36,346,99,69,24,367,55,2])
boolean_masking

array([  1,   2,   3,   4,  55, 394,  32,  53,   4,  32,   5,  36, 346,
        99,  69,  24, 367,  55,   2])

In [51]:
boolean_masking[boolean_masking>50]

array([ 55, 394,  53, 346,  99,  69, 367,  55])