In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [8]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [10]:
# Indexing in multi-dimensional array
print(arr[0][1])

2


In [17]:
arr[0,1]

np.int64(2)

In [18]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [19]:
# 3D ARRAY
arr3d = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [21]:
arr3d.shape

(2, 2, 3)

In [22]:
print(arr3d[0,1,2])

6


In [23]:
print(arr3d[:,0,:])

[[1 2 3]
 [7 8 9]]
